services:
  srv-pl-dt-eng:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    image: img-pl-dt-eng
    container_name: ctnr-pl-dt-eng
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: "no"
    environment:
      - USER_ID=${UID}
      - GROUP_ID=${GID}